version: '3'

services:

  pricepredictor:
          image: mspricepredictor
          container_name: mspricepredictor.io
          build:
              context: ../
              dockerfile: Laptop_price_predictor/Dockerfile
          ports:
          - 8080:8080
          networks:
            - price_network
networks:
  price_network:
    external : true
